version: 1.0.{build}
configuration:
- Debug
- Release
platform: Any CPU
environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
branches:
  only:
  - master
before_build:
- appveyor-retry dotnet restore -v Minimal
build_script:
- dotnet build -c Release --no-dependencies
after_build:
- dotnet pack -c Release --no-build
#build:
  #project: Straight-Line.xproj
  #verbosity: minimal
deploy:
- provider: S3
  aspnet_core_force_restart: true
  access_key_id: AKIAIY2ZMB6G7OJY5B3Q
  secret_access_key:
    secure: vuy+rfshYn99da+ZunmZn95XvpAeMFawPduxXtC0OruwPRyZPWEQDt3c8qMDtAZt
  region: eu-west-1
  bucket: codedeploy-poulw
  folder: master
  set_public: false
  encrypt: false
  on:
    branch: master
notifications:
- provider: Webhook
  url: http://mvc.tech-flex.com/api/appveyor
  method: POST
  on_build_success: true
  on_build_failure: false
  on_build_status_changed: false
cache:
- '%USERPROFILE%\.nuget\packages'