version: 1.0.{build}
branches:
  only:
  - master
before_build:
- ps: dotnet restore
build:
  project: Straight-Line.xproj
  verbosity: minimal
deploy:
- provider: S3
  aspnet_core_force_restart: true
  access_key_id: AKIAIY2ZMB6G7OJY5B3Q
  secret_access_key:
    secure: vuy+rfshYn99da+ZunmZn95XvpAeMFawPduxXtC0OruwPRyZPWEQDt3c8qMDtAZt
  region: eu-west-1
  bucket: codedeploy-poulw
  folder: master
  set_public: false
  encrypt: false
  on:
    branch: master
notifications:
- provider: Webhook
  url: http://mvc.tech-flex.com/api/appveyor
  method: POST
  on_build_success: true
  on_build_failure: false
  on_build_status_changed: false