version: 1.0.{build}
configuration:
- Debug
#- Release
platform: Any CPU
environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
branches:
  only:
  - master
init:
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
before_build:
- appveyor-retry dotnet restore -v Minimal
build_script:
- dotnet build -c Release --no-dependencies
after_build:
- dotnet pack -c Release --no-build
#build:
  #project: Straight-Line.xproj
  #verbosity: minimal
#deploy:
#- provider: Environment
  #aspnet_core_force_restart: true
  #name: CodeDeploy
  #on:
    #branch: master
deploy:
- provider: S3
  aspnet_core_force_restart: true
  access_key_id: AKIAILYVH5BOGV3E6HVQ
  secret_access_key:
    secure: UJSO1WCJWmaeCFcMAyz8mbicEpHQq2/hrFM0tNVnfb4zNwVCpgYwaOjDbYlqUzQF
  region: eu-west-1
  bucket: new-bucket-25290414
  artifact: "mvc-$(APPVEYOR_REPO_COMMIT).tar.gz"
  encrypt: true
  on:
    branch: master
notifications:
- provider: Webhook
  url: http://mvc.tech-flex.com/api/appveyor
  method: POST
  on_build_success: true
  on_build_failure: false
  on_build_status_changed: false
cache:
- '%USERPROFILE%\.nuget\packages'