version: 1.0.{build}
configuration:
- Debug
#- Release
platform: Any CPU
environment:  
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
branches:
  only:
  - master
init:
#- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
before_build:
- npm install -g webpack
- appveyor-retry dotnet restore -v Minimal
build_script:
- dotnet build -c Release --no-dependencies --version-suffix %LABEL%
after_build:
- dotnet publish -c Release -r ubuntu.14.04-x64 --version-suffix %LABEL% -o bin\publish
artifacts:
  - path: bin\publish 
deploy:
- provider: S3
  access_key_id: AKIAILYVH5BOGV3E6HVQ
  secret_access_key:
    secure: UJSO1WCJWmaeCFcMAyz8mbicEpHQq2/hrFM0tNVnfb4zNwVCpgYwaOjDbYlqUzQF
  region: eu-west-1
  bucket: new-bucket-25290414
  folder: release
  set_public: true
  encrypt: true
  on:
    branch: master
before_deploy:
after_deploy:
- ps: Invoke-WebRequest -UseBasicParsing http://mvc.tech-flex.com/Api/GitPullUpdateServer -ContentType "application/json" -Method POST -Body "{ 'key':'0981j2d982uf918h2f981h2f98h' }"